"use client";
import type { Metadata } from "next";
import { Roboto , Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "../components/Providers";
import { ThemeProvider } from "../components/theme-provider";
const roboto  = Roboto ({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body
        className={`${roboto.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
      >
        <Providers>
        {children}
        </Providers>
      </ThemeProvider>
      </body>
    </html>
  );
}
